name: Build CV
run-name: Rebuild triggered by @${{github.actor}}
on:
  push:
    branches:
      - main

permissions:
  write-all
  
concurrency:
  group: "pages"
  cancel-in-progress: false 
  
jobs:
  build-cv:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Build the CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: source/Matthew-Hammond-CV.tex
          
      - name: Delete previous release(s)
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest CV
          draft: false
          prerelease: false
          
      - name: Upload CV
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Matthew-Hammond-CV.pdf
          asset_name: Matthew-Hammond-CV.pdf
          asset_content_type: pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
